# Generated by Django 4.1.7 on 2023-02-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechArionApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ManyToManyField(blank=True, to='TechArionApp.productimagemodel')),
            ],
        ),
    ]
